In [1]:
"""This is video reader with all operations inside fnctions, so they can be called on 
    each frame out of a set of frames, and each video out of a set of videos
    """

'This is video reader with all operations inside fnctions, so they can be called on \n    each frame out of a set of frames, and each video out of a set of videos\n    '

In [2]:
"""Imports"""
import matplotlib.pyplot as plt #for maknig plots inside the notebook
import skimage
import skvideo.io
from skvideo.io import vreader, ffprobe
from skimage import measure, morphology, feature
from skimage.filters import *
from skimage.morphology import *
from operator import attrgetter
import numpy as np
import math
from itertools import chain
#from functools import partial, update_wrapper
from scipy import ndimage 
from glob import glob
import seaborn as sns
from collections import OrderedDict 
#import antigravity

blob_doh = skimage.feature.blob_doh

In [3]:
"""Functions"""
# apply total thresholding to each of a list of frames; filter slides with wrong number

def total_threshold_filter(frame, frame_no, transition_threshold, class_thresh,
                           broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                           classes, transitions, times): 
    
   
    
   # ---setup image and detect blobs ----------------
    thresh_img = frame > threshold_isodata(frame)# binary image
        
    phighlight = binary_opening(thresh_img, square(14))
    img = np.copy(frame)
    img[phighlight==0] = 0
    pblobs =blob_doh(img, min_sigma = 10, max_sigma = 16, threshold = 0.007, num_sigma= 15, overlap=0.6)
        
    ghighlight = opening(
        white_tophat(gaussian(thresh_img, sigma=0.2), square(14)),
                                   disk(4))
    img = np.copy(frame)
    img[ghighlight==0] = 0
    gblobs =blob_doh(img, min_sigma = 8, max_sigma = 16, threshold = 0.007, num_sigma= 15, overlap=0.5)
    

    ngblobs = len(gblobs)
    npblobs = len(pblobs) 
    num_blobs = ngblobs + npblobs
            
    plas_on_glas_dists =[connect((pblob[1], pblob[0]),m_bond, gblobs) for pblob in pblobs]
    num_mconnections = reducer(plas_on_glas_dists)


    glas_on_glas_dists =[connect((gblobs[i][1], gblobs[i][0]),g_bond, gblobs[i+1:]) for i in range(ngblobs-1)]
    num_gconnections = reducer(glas_on_glas_dists)



    num_connections = sum([num_gconnections,num_mconnections])
    
    #----------------------filter------------------------- can use actual filter
    test = (num_connections >= expected_connections and num_blobs>=expected_blobs)
    if test: # keep frames that have enough paricles, and are not transitions
        clas =sideify(num_gconnections, num_mconnections )
        classes[clas]+=1 
            #print(clas)
        
        if clas == 'ucf':
            #broken_count += 1
            #class_num = 0
            #print('ucf')
            pass
        else:
            if origin == 'ucf':
                origin = last_class
                #print("reset origin", origin)
            if clas == last_class:
                class_num += 1
                #print("class_num: %s" %class_num)
            else:
                class_num = 0
                #print("class_reset")
                #print("class_num: %s" %class_num)
            if class_num >= class_thresh: 
                if broken_count >= transition_threshold or clas != origin:
                    transitions[origin + "->" + clas]+=1
                    
                    between_time = frame_no - state_start                               
                    times[origin + "->" + clas][0].append(between_time)  

                    stable_time = last_whole - state_start
                    times[origin + "->" + clas][1].append(stable_time)

                    unstable_time = frame_no - last_whole                      
                    times[origin + "->" + clas][2].append(unstable_time)
                
                    state_start = frame_no
                    
                    #print(origin + "->" + clas)
                    origin = clas
                    #print("origin: %s" %origin)
                broken_count = 0
                #print("broken_count: %s" %broken_count)    
                last_whole = frame_no
                
            filtrate_len += 1 
            last_class = clas
            
            
    else:
        #print("broken")
        class_num = 0
        #print("class_num: %s" %class_num)
        broken_count += 1
        #print("broken_count: %s" %broken_count)

    return [broken_count, class_num, origin, last_class, last_whole,state_start, filtrate_len]



        
# take largest isodata image region, and return aclassification
def sideify( num_gconnections, num_mconnections):    
    if num_mconnections == 2 and num_gconnections ==3:# and num_mconnections==4: #gtotallengths>48
        return "t"
    elif num_mconnections == 3 and num_gconnections ==2:# and num_mconnections == 4:
        return "c"
    else:
        return "ucf"

def reducer(connections):
    return sum(connections)    
def connect(cv, radius, bloblist): # center of blob2, radius of all blobs, list of other blobs
    num_connections = 0
    norm_radius = 15
    for blob2 in bloblist:
        cv2 = (blob2[1], blob2[0]) # center of blob2
        vector_d = vector_dist(cv, cv2)
        if vector_d <= 2*radius and vector_d > .2*radius: # blob centers closer than diameter of one blob
            num_connections += 1
        else:
            pass
    return (num_connections)

def vector_dist(v1, v2): # euclidean distance between 2 points
    return math.sqrt(np.sum([(v1[i] - v2[i])**2 for i in range(len(v1))]))

def third_item(l1):
    return l1[2]   

In [ ]:
"""Pipeline for lists of frames"""
""""""
"""Pipeline for videos:"""
# initialize frame lists
filenames = glob("./tchakamau/W*glass/4*avi")# +glob("./tchakamau/W*half/*_[1][0,1,2,3,4,7,8,9]*.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 3
num_full_keys = 3
num_tran_keys = 2
num_lengths = 3
trans_threshes = np.linspace(30, 50, 2)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes =[20,30]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
g_bond = 15*1.15
m_bond = 15*1.35
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, g_bond, m_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        T_transitions = [[[[[] for i in range(num_tran_keys)] for j in range(num_tran_keys)] for k in range(num_lengths)] 
                          for l in range(len(filenames))]
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            #frame_vid = frames[:, :, :, 2]# making videos ino a frame list
            #print(frames)



            classes = [("t",0), ("c",0), ("ucf",0)]
            transitions = [("t->t",0), ("t->c",0),
                          ("c->t" ,0), ("c->c",0)]
            times = [("t->t",[[] for i in range(num_lengths)]), ("t->c",[[] for i in range(num_lengths)]),
                          ("c->t" ,[[] for i in range(num_lengths)]), ("c->c",[[] for i in range(num_lengths)])]

            transitions = OrderedDict(transitions)
            times = OrderedDict(times)            
            classes = OrderedDict(classes)
            broken_count = 0
            class_num = 0
            origin = 'ucf'
            last_class = 'ucf'
            last_whole = 0
            state_start = 0
            frame_no = 0
            for fr in frames:
                frame = fr[:, :, 2]
                frame_no += 1
                num_total_frames += 1
                org = total_threshold_filter(frame, frame_no, trans_fil, class_thresh,
                                             broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                                              classes, transitions, times)
                broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len = org
            filtered_len = filtrate_len
            #----------------------------------------------------------------
            ckeys = list(classes.keys())
            clcs = [classes[x] for x in ckeys] # list of frame nums per class
            
            tkeys = list(times.keys())
            tims = [times[x] for x in tkeys]
            
            trkeys = list(transitions.keys())
            trans = [transitions[x] for x in trkeys] #num of each transition
            #ucf = len(sides["ucf"])

            #Top_bottoms[vidnum,:] = [slcs[i] for i in range(len(skeys))]
            Full_classif[vidnum,:] = clcs
            N_transitions[vidnum,:] = np.reshape(trans, (num_tran_keys, num_tran_keys))             
            T_transitions[vidnum] = np.moveaxis(np.reshape(tims, (num_tran_keys, num_tran_keys,num_lengths)),
                                                  [0,1,2], [1,2,0])
            print("T threshold: %s" %trans_fil)
            print("C threshold: %s" %class_thresh)
            print(N_transitions[vidnum,:])
            print(T_transitions[vidnum])
            print(Full_classif[vidnum,:])
        trans_runs[index] = [[Full_classif, (N_transitions, T_transitions), (trans_fil, class_thresh), num_top_keys, num_full_keys,
                                 num_tran_keys,  ckeys, num_tran_keys, num_total_frames], thresholds, params]
        index += 1
        #---------------------------------------------------------------------------------

#-----------------------------------------------------------------------

np.save('trans_runs_glass15.5.npy',trans_runs)


['./tchakamau\\Washed15vglass\\45660_15Vpp_0.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_1.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_10.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_11.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_2.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_3.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_4.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_5.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_6.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_7.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_8.avi', './tchakamau\\Washed15vglass\\45660_15Vpp_9.avi']
Number files:  12
Processing vid 0 : ./tchakamau\Washed15vglass\45660_15Vpp_0.avi
T threshold: 30.0
C threshold: 20
[[2. 1.]
 [1. 4.]]
[[[list([91, 619]) list([9041])]
  [list([586]) list([1388, 494, 297, 558])]]

 [[list([0, 43]) list([8509])]
  [list([451]) list([461, 147, 0, 183])]]

 [[list([91, 576]) list([532])]
  [list([135]) list([927, 347, 297, 375])]]]
[7434. 1665. 1382.]
Processing v

T threshold: 30.0
C threshold: 30
[[1. 1.]
 [1. 3.]]
[[[list([610]) list([9041])]
  [list([591]) list([1493, 831, 562])]]

 [[list([24]) list([8499])]
  [list([346]) list([433, 137, 133])]]

 [[list([586]) list([542])]
  [list([245]) list([1060, 694, 429])]]]
[7434. 1665. 1382.]
Processing vid 1 : ./tchakamau\Washed15vglass\45660_15Vpp_1.avi
T threshold: 30.0
C threshold: 30
[[ 7.  1.]
 [ 0. 20.]]
[[[list([1157, 576, 210, 388, 257, 173, 222]) list([955])]
  [list([])
   list([516, 338, 262, 5031, 335, 703, 678, 639, 300, 662, 287, 819, 725, 1155, 1129, 388, 527, 477, 245, 1164])]]

 [[list([0, 333, 4, 109, 7, 9, 5]) list([2])]
  [list([])
   list([183, 12, 24, 1, 107, 47, 390, 56, 2, 508, 108, 121, 613, 745, 820, 306, 427, 264, 88, 857])]]

 [[list([1157, 243, 206, 279, 250, 164, 217]) list([953])]
  [list([])
   list([333, 326, 238, 5030, 228, 656, 288, 583, 298, 154, 179, 698, 112, 410, 309, 82, 100, 213, 157, 307])]]]
[ 1873. 10026.  3723.]
Processing vid 2 : ./tchakamau\Washed15vgl

T threshold: 50.0
C threshold: 20
[[1. 2.]
 [1. 2.]]
[[[list([2702]) list([1353, 4232])]
  [list([3097]) list([1046, 7441])]]

 [[list([0]) list([1003, 2531])]
  [list([2194]) list([379, 6191])]]

 [[list([2702]) list([350, 1701])]
  [list([903]) list([667, 1250])]]]
[ 2156. 15136.  6402.]
Processing vid 3 : ./tchakamau\Washed15vglass\45660_15Vpp_11.avi
T threshold: 50.0
C threshold: 20
[[0. 1.]
 [1. 1.]]
[[[list([]) list([8032])]
  [list([2853]) list([1582])]]

 [[list([]) list([7319])]
  [list([2358]) list([310])]]

 [[list([]) list([713])]
  [list([495]) list([1272])]]]
[4655. 2319. 3720.]
Processing vid 4 : ./tchakamau\Washed15vglass\45660_15Vpp_2.avi
T threshold: 50.0
C threshold: 20
[[1. 2.]
 [2. 3.]]
[[[list([517]) list([76, 2078])]
  [list([1140, 535]) list([330, 939, 4377])]]

 [[list([5]) list([0, 1563])]
  [list([887, 4]) list([0, 115, 2486])]]

 [[list([512]) list([76, 515])]
  [list([253, 531]) list([330, 824, 1891])]]]
[1414. 4238.  767.]
Processing vid 5 : ./tchakamau\Wa