In [1]:
"""This is video reader with all operations inside fnctions, so they can be called on 
    each frame out of a set of frames, and each video out of a set of videos
    """

'This is video reader with all operations inside fnctions, so they can be called on \n    each frame out of a set of frames, and each video out of a set of videos\n    '

In [2]:
"""Imports"""
import matplotlib.pyplot as plt #for maknig plots inside the notebook
import skimage
import skvideo.io
from skvideo.io import vreader, ffprobe
from skimage import measure, morphology, feature
from skimage.filters import *
from skimage.morphology import *
from operator import attrgetter
import numpy as np
import math
from itertools import chain
#from functools import partial, update_wrapper
from scipy import ndimage 
from glob import glob
import seaborn as sns
from collections import OrderedDict 
#import antigravity

blob_doh = skimage.feature.blob_doh
blob_dog = skimage.feature.blob_dog

In [3]:
"""Functions"""
# apply total thresholding to each of a list of frames; filter slides with wrong number

def total_threshold_filter(frame, frame_no, transition_threshold, class_thresh,
                           broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                           classes, transitions, times): 
    
   
    
   # ---setup image and detect blobs ----------------
    thresh_img = frame > threshold_isodata(frame)# binary image
        
    phighlight = binary_opening(thresh_img, square(14))
    img = np.copy(frame)
    img[phighlight==0] = 0
    pblobs =blob_doh(img, min_sigma = 10, max_sigma = 16, threshold = 0.007, num_sigma= 15, overlap=0.6)
        
    ghighlight = opening(
        white_tophat(gaussian(thresh_img, sigma=0.2), square(14)),
                                   disk(4))
    img = np.copy(frame)
    img[ghighlight==0] = 0
    gblobs =blob_dog(img, min_sigma = 8, max_sigma = 12, threshold = 0.2, overlap=0.5)
    

    ngblobs = len(gblobs)
    npblobs = len(pblobs) 
    num_blobs = ngblobs + npblobs
            
    plas_on_glas_dists =[connect((pblob[1], pblob[0]),m_bond, gblobs) for pblob in pblobs]
    num_mconnections = reducer(plas_on_glas_dists)


    glas_on_glas_dists =[connect((gblobs[i][1], gblobs[i][0]),g_bond, gblobs[i+1:]) for i in range(ngblobs-1)]
    num_gconnections = reducer(glas_on_glas_dists)



    num_connections = sum([num_gconnections,num_mconnections])
    
    #----------------------filter------------------------- can use actual filter
    test = (num_connections >= expected_connections and num_blobs>=expected_blobs)
    if test: # keep frames that have enough paricles, and are not transitions
        clas =sideify(num_gconnections, num_mconnections )
        classes[clas]+=1 
            #print(clas)
        
        if clas == 'ucf':
            #broken_count += 1
            #class_num = 0
            #print('ucf')
            pass
        else:
            if origin == 'ucf':
                origin = last_class
                #print("reset origin", origin)
            if clas == last_class:
                class_num += 1
                #print("class_num: %s" %class_num)
            else:
                class_num = 0
                #print("class_reset")
                #print("class_num: %s" %class_num)
            if class_num >= class_thresh: 
                if broken_count >= transition_threshold or clas != origin:
                    transitions[origin + "->" + clas]+=1
                    
                    between_time = frame_no - state_start                               
                    times[origin + "->" + clas][0].append(between_time)  

                    stable_time = last_whole - state_start
                    times[origin + "->" + clas][1].append(stable_time)

                    unstable_time = frame_no - last_whole                      
                    times[origin + "->" + clas][2].append(unstable_time)
                
                    state_start = frame_no
                    
                    #print(origin + "->" + clas)
                    origin = clas
                    #print("origin: %s" %origin)
                broken_count = 0
                #print("broken_count: %s" %broken_count)    
                last_whole = frame_no
                
            filtrate_len += 1 
            last_class = clas
            
            
    else:
        #print("broken")
        class_num = 0
        #print("class_num: %s" %class_num)
        broken_count += 1
        #print("broken_count: %s" %broken_count)

    return [broken_count, class_num, origin, last_class, last_whole,state_start, filtrate_len]



        
# take largest isodata image region, and return aclassification
def sideify( num_gconnections, num_mconnections):    
    if num_mconnections == 2 and num_gconnections ==3:# and num_mconnections==4: #gtotallengths>48
        return "t"
    elif num_mconnections == 3 and num_gconnections ==2:# and num_mconnections == 4:
        return "c"
    else:
        return "ucf"

def reducer(connections):
    return sum(connections)    
def connect(cv, radius, bloblist): # center of blob2, radius of all blobs, list of other blobs
    num_connections = 0
    norm_radius = 15
    for blob2 in bloblist:
        cv2 = (blob2[1], blob2[0]) # center of blob2
        vector_d = vector_dist(cv, cv2)
        if vector_d <= 2*radius and vector_d > .2*radius: # blob centers closer than diameter of one blob
            num_connections += 1
        else:
            pass
    return (num_connections)

def vector_dist(v1, v2): # euclidean distance between 2 points
    return math.sqrt(np.sum([(v1[i] - v2[i])**2 for i in range(len(v1))]))

def third_item(l1):
    return l1[2]   

In [ ]:

"""Pipeline for lists of frames"""
""""""
"""Pipeline for videos:"""
# initialize frame lists
filenames = glob("./tchakamau/De*styrene/*[6].avi")# +glob("./tchakamau/W*half/*_[1][0,1,2,3,4,7,8,9]*.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 3
num_full_keys = 3
num_tran_keys = 2
num_lengths = 3
trans_threshes = np.linspace(5, 100, 20)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes = np.linspace(5, 100, 20)#[15, 22, 30]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
g_bond = 15*1
m_bond = 15*1.15
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, g_bond, m_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        T_transitions = [[[[[] for i in range(num_tran_keys)] for j in range(num_tran_keys)] for k in range(num_lengths)] 
                          for l in range(len(filenames))]
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            #frame_vid = frames[:, :, :, 2]# making videos ino a frame list
            #print(frames)



            classes = [("t",0), ("c",0), ("ucf",0)]
            transitions = [("t->t",0), ("t->c",0),
                          ("c->t" ,0), ("c->c",0)]
            times = [("t->t",[[] for i in range(num_lengths)]), ("t->c",[[] for i in range(num_lengths)]),
                          ("c->t" ,[[] for i in range(num_lengths)]), ("c->c",[[] for i in range(num_lengths)])]

            transitions = OrderedDict(transitions)
            times = OrderedDict(times)            
            classes = OrderedDict(classes)
            broken_count = 0
            class_num = 0
            origin = 'ucf'
            last_class = 'ucf'
            last_whole = 0
            state_start = 0
            frame_no = 0
            for fr in frames:
                frame = fr[:, :, 2]
                frame_no += 1
                num_total_frames += 1
                org = total_threshold_filter(frame, frame_no, trans_fil, class_thresh,
                                             broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                                              classes, transitions, times)
                broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len = org
            filtered_len = filtrate_len
            #----------------------------------------------------------------
            ckeys = list(classes.keys())
            clcs = [classes[x] for x in ckeys] # list of frame nums per class
            
            tkeys = list(times.keys())
            tims = [times[x] for x in tkeys]
            
            trkeys = list(transitions.keys())
            trans = [transitions[x] for x in trkeys] #num of each transition
            #ucf = len(sides["ucf"])

            #Top_bottoms[vidnum,:] = [slcs[i] for i in range(len(skeys))]
            Full_classif[vidnum,:] = clcs
            N_transitions[vidnum,:] = np.reshape(trans, (num_tran_keys, num_tran_keys))             
            T_transitions[vidnum] = np.moveaxis(np.reshape(tims, (num_tran_keys, num_tran_keys,num_lengths)),
                                                  [0,1,2], [1,2,0])
            print("T threshold: %s" %trans_fil)
            print("C threshold: %s" %class_thresh)
            print(N_transitions[vidnum,:])
            print(T_transitions[vidnum])
            print(Full_classif[vidnum,:])
        trans_runs[index] = [[Full_classif, (N_transitions, T_transitions), (trans_fil, class_thresh), num_top_keys, num_full_keys,
                                 num_tran_keys,  ckeys, num_tran_keys, num_total_frames], thresholds, params]
        index += 1
        #---------------------------------------------------------------------------------

#-----------------------------------------------------------------------

np.save('trans_runs_destyrene_error.npy',trans_runs)


['./tchakamau\\Density_matchedstyrene\\45696_15Vpp_6.avi']
Number files:  1
Processing vid 0 : ./tchakamau\Density_matchedstyrene\45696_15Vpp_6.avi
T threshold: 5.0
C threshold: 5.0
[[ 55.  10.]
 [ 10. 168.]]
[[[list([19, 61, 71, 45, 159, 1926, 188, 3339, 33, 36, 28, 87, 28, 159, 169, 117, 23, 189, 160, 123, 90, 137, 28, 12, 21, 644, 177, 2157, 13, 31, 139, 206, 75, 19, 19, 3519, 43, 27, 146, 3140, 20, 276, 65, 21, 134, 114, 230, 67, 2034, 120, 415, 15, 85, 27, 63])
   list([534, 60, 45, 1562, 214, 151, 147, 56, 58, 417])]
  [list([448, 57, 491, 415, 507, 82, 1343, 348, 49, 199])
   list([273, 18, 28, 219, 176, 27, 23, 113, 190, 31, 96, 25, 324, 636, 217, 14, 10, 21, 36, 22, 213, 319, 10, 19, 17, 748, 183, 261, 712, 22, 694, 291, 1405, 1468, 283, 124, 793, 64, 70, 42, 96, 331, 140, 220, 30, 100, 68, 29, 144, 210, 245, 58, 125, 13, 72, 88, 251, 60, 84, 27, 14, 31, 17, 31, 971, 113, 70, 148, 178, 77, 246, 287, 229, 23, 1868, 17, 18, 16, 16, 370, 199, 31, 197, 193, 107, 50, 331, 903, 909,

T threshold: 5.0
C threshold: 20.0
[[ 27.   8.]
 [  8. 112.]]
[[[list([120, 45, 159, 1926, 82, 106, 53, 195, 111, 476, 125, 98, 100, 2660, 53, 3440, 70, 276, 96, 64, 61, 113, 69, 161, 67, 2034, 552])
   list([3917, 186, 322, 1562, 3797, 380, 257, 882])]
  [list([479, 471, 1162, 670, 696, 164, 2214, 468])
   list([397, 102, 54, 226, 113, 81, 252, 423, 278, 240, 339, 607, 700, 238, 206, 243, 241, 250, 694, 291, 954, 451, 1468, 283, 124, 793, 64, 112, 96, 222, 390, 100, 97, 144, 170, 57, 109, 119, 58, 138, 94, 89, 228, 60, 121, 944, 74, 69, 59, 118, 533, 2202, 165, 201, 229, 218, 269, 50, 356, 879, 909, 465, 790, 126, 126, 126, 189, 106, 986, 229, 354, 35, 205, 207, 170, 60, 96, 134, 780, 39, 78, 78, 461, 1276, 6412, 2523, 956, 173, 564, 206, 58, 60, 151, 117, 57, 186, 227, 584, 59, 89, 633, 2355, 540, 415, 1474, 553, 2190, 162, 264, 1539, 83, 254])]]

 [[list([3, 20, 50, 1584, 31, 26, 6, 81, 62, 11, 50, 4, 9, 2075, 13, 3344, 3, 234, 6, 30, 33, 13, 34, 131, 24, 2003, 175])
   list([3195, 

T threshold: 5.0
C threshold: 40.0
[[13.  8.]
 [ 8. 94.]]
[[[list([204, 1926, 241, 2716, 3507, 372, 64, 174, 69, 161, 67, 2004, 552])
   list([3917, 1093, 344, 2095, 3832, 380, 212, 935])]
  [list([599, 471, 1360, 642, 802, 164, 2289, 468])
   list([573, 339, 333, 84, 339, 278, 240, 339, 655, 652, 238, 206, 243, 241, 290, 654, 291, 954, 451, 1468, 283, 124, 793, 64, 154, 75, 126, 75, 390, 100, 97, 144, 227, 109, 177, 138, 183, 288, 121, 1270, 116, 2086, 165, 201, 265, 184, 317, 356, 880, 912, 461, 831, 85, 126, 126, 98, 91, 951, 229, 801, 230, 123, 141, 785, 78, 78, 461, 1276, 6443, 2492, 956, 1001, 60, 151, 174, 186, 227, 584, 148, 633, 1134, 205, 963, 540, 415, 1474, 553, 2190, 162, 264, 1539, 83, 254, 3505])]]

 [[list([0, 1564, 11, 2055, 3321, 214, 10, 13, 14, 60, 4, 1908, 155])
   list([3175, 61, 55, 1469, 3023, 3, 24, 13])]
  [list([61, 45, 51, 53, 32, 16, 826, 42])
   list([127, 124, 0, 4, 171, 221, 152, 124, 42, 566, 129, 159, 182, 176, 166, 585, 208, 897, 385, 1420, 238, 78, 7