In [1]:
"""This is video reader with all operations inside fnctions, so they can be called on 
    each frame out of a set of frames, and each video out of a set of videos
    """

'This is video reader with all operations inside fnctions, so they can be called on \n    each frame out of a set of frames, and each video out of a set of videos\n    '

In [2]:
"""Imports"""
import matplotlib.pyplot as plt #for maknig plots inside the notebook
import skimage
import skvideo.io
from skvideo.io import vreader, ffprobe
from skimage import measure, morphology, feature
from skimage.filters import *
from skimage.morphology import *
from operator import attrgetter
import numpy as np
import math
from itertools import chain
#from functools import partial, update_wrapper
from scipy import ndimage 
#from pims import pipeline, Video
from glob import glob
import seaborn as sns
from collections import OrderedDict 
#import antigravity

In [ ]:
"""Pipeline for lists of frames"""
""""""
"""Pipeline for videos:"""
# initialize frame lists
filenames =glob("./tchakamau/W*half/*_[4,8]*.avi") +glob("./tchakamau/W*half/*a.avi")#glob("./tchakamau/W*half/*_21*a.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 4
num_full_keys = 4
num_tran_keys = 3
num_lengths = 3 # ways to measure the time betwen transitions, as it were
trans_threshes = np.linspace(40, 60, 2)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes =[22,35]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
p_bond = 15*1.35
g_bond = 15*1.15
fp_bond = 15*1.75
fg_bond = 15*1.8
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, p_bond, g_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        #Top_bottoms = np.zeros((len(filenames), num_top_keys))
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        T_transitions = [[[[[] for i in range(len(filenames))] for j in range(num_lengths)] for k in range(num_tran_keys)] 
                          for l in range(num_tran_keys)]
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            

['./tchakamau\\Washed15vhalf\\45657_15Vpp_101_a.avi', './tchakamau\\Washed15vhalf\\45662_15Vpp_111_a.avi', './tchakamau\\Washed15vhalf\\45686_15Vpp_131_pushed_a.avi', './tchakamau\\Washed15vhalf\\45693_15Vpp_121_a.avi', './tchakamau\\Washed15vhalf\\45706_15Vpp_71_a.avi', './tchakamau\\Washed15vhalf\\45706_15Vpp_72_ba.avi', './tchakamau\\Washed15vhalf\\45734_15Vpp_8.avi', './tchakamau\\Washed15vhalf\\45755_15Vpp_141_a.avi', './tchakamau\\Washed15vhalf\\45782_15Vpp_21_a.avi', './tchakamau\\Washed15vhalf\\45782_15Vpp_22_ba.avi', './tchakamau\\Washed15vhalf\\45782_15Vpp_31_a.avi', './tchakamau\\Washed15vhalf\\45782_15Vpp_32_ba.avi', './tchakamau\\Washed15vhalf\\45782_15Vpp_33_ca.avi', './tchakamau\\Washed15vhalf\\45782_15Vpp_4.avi']
Number files:  14
Processing vid 0 : ./tchakamau\Washed15vhalf\45657_15Vpp_101_a.avi
T threshold: 40.0
C threshold: 22
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 6.]]
[[[list([]) list([]) list([3757])]
  [list([]) list([]) list([])]
  [list([]) list([]) list([1907, 445, 2