In [1]:
"""This is video reader with all operations inside fnctions, so they can be called on 
    each frame out of a set of frames, and each video out of a set of videos
    """

'This is video reader with all operations inside fnctions, so they can be called on \n    each frame out of a set of frames, and each video out of a set of videos\n    '

In [2]:
"""Imports"""
import matplotlib.pyplot as plt #for maknig plots inside the notebook
import skimage
import skvideo.io
from skvideo.io import vreader, ffprobe
from skimage import measure, morphology, feature
from skimage.filters import *
from skimage.morphology import *
from operator import attrgetter
import numpy as np
import math
from itertools import chain
#from functools import partial, update_wrapper
from scipy import ndimage 
from glob import glob
import seaborn as sns
from collections import OrderedDict 
#import antigravity

blob_doh = skimage.feature.blob_doh
blob_dog = skimage.feature.blob_dog

In [3]:
"""Functions"""
# apply total thresholding to each of a list of frames; filter slides with wrong number

def total_threshold_filter(frame, frame_no, transition_threshold, class_thresh,
                           broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                           classes, transitions, times): 
    
   
    
   # ---setup image and detect blobs ----------------
    thresh_img = frame > threshold_isodata(frame)# binary image
        
    phighlight = binary_opening(thresh_img, square(14))
    img = np.copy(frame)
    img[phighlight==0] = 0
    pblobs =blob_doh(img, min_sigma = 10, max_sigma = 16, threshold = 0.007, num_sigma= 15, overlap=0.6)
        
    ghighlight = opening(
        white_tophat(gaussian(thresh_img, sigma=0.2), square(14)),
                                   disk(4))
    img = np.copy(frame)
    img[ghighlight==0] = 0
    gblobs =blob_dog(img, min_sigma = 8, max_sigma = 12, threshold = 0.2, overlap=0.5)
    

    ngblobs = len(gblobs)
    npblobs = len(pblobs) 
    num_blobs = ngblobs + npblobs
            
    plas_on_glas_dists =[connect((pblob[1], pblob[0]),m_bond, gblobs) for pblob in pblobs]
    num_mconnections = reducer(plas_on_glas_dists)


    glas_on_glas_dists =[connect((gblobs[i][1], gblobs[i][0]),g_bond, gblobs[i+1:]) for i in range(ngblobs-1)]
    num_gconnections = reducer(glas_on_glas_dists)



    num_connections = sum([num_gconnections,num_mconnections])
    
    #----------------------filter------------------------- can use actual filter
    test = (num_connections >= expected_connections and num_blobs>=expected_blobs)
    if test: # keep frames that have enough paricles, and are not transitions
        clas =sideify(num_gconnections, num_mconnections )
        classes[clas]+=1 
            #print(clas)
        
        if clas == 'ucf':
            #broken_count += 1
            #class_num = 0
            #print('ucf')
            pass
        else:
            if origin == 'ucf':
                origin = last_class
                #print("reset origin", origin)
            if clas == last_class:
                class_num += 1
                #print("class_num: %s" %class_num)
            else:
                class_num = 0
                #print("class_reset")
                #print("class_num: %s" %class_num)
            if class_num >= class_thresh: 
                if broken_count >= transition_threshold or clas != origin:
                    transitions[origin + "->" + clas]+=1
                    
                    between_time = frame_no - state_start                               
                    times[origin + "->" + clas][0].append(between_time)  

                    stable_time = last_whole - state_start
                    times[origin + "->" + clas][1].append(stable_time)

                    unstable_time = frame_no - last_whole                      
                    times[origin + "->" + clas][2].append(unstable_time)
                
                    state_start = frame_no
                    
                    #print(origin + "->" + clas)
                    origin = clas
                    #print("origin: %s" %origin)
                broken_count = 0
                #print("broken_count: %s" %broken_count)    
                last_whole = frame_no
                
            filtrate_len += 1 
            last_class = clas
            
            
    else:
        #print("broken")
        class_num = 0
        #print("class_num: %s" %class_num)
        broken_count += 1
        #print("broken_count: %s" %broken_count)

    return [broken_count, class_num, origin, last_class, last_whole,state_start, filtrate_len]



        
# take largest isodata image region, and return aclassification
def sideify( num_gconnections, num_mconnections):    
    if num_mconnections == 2 and num_gconnections ==3:# and num_mconnections==4: #gtotallengths>48
        return "t"
    elif num_mconnections == 3 and num_gconnections ==2:# and num_mconnections == 4:
        return "c"
    else:
        return "ucf"

def reducer(connections):
    return sum(connections)    
def connect(cv, radius, bloblist): # center of blob2, radius of all blobs, list of other blobs
    num_connections = 0
    norm_radius = 15
    for blob2 in bloblist:
        cv2 = (blob2[1], blob2[0]) # center of blob2
        vector_d = vector_dist(cv, cv2)
        if vector_d <= 2*radius and vector_d > .2*radius: # blob centers closer than diameter of one blob
            num_connections += 1
        else:
            pass
    return (num_connections)

def vector_dist(v1, v2): # euclidean distance between 2 points
    return math.sqrt(np.sum([(v1[i] - v2[i])**2 for i in range(len(v1))]))

def third_item(l1):
    return l1[2]   

In [ ]:
"""Pipeline for lists of frames"""
""""""
"""Pipeline for videos:"""
# initialize frame lists
filenames = glob("./tchakamau/De*styrene/*[0-9].avi")# +glob("./tchakamau/W*half/*_[1][0,1,2,3,4,7,8,9]*.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 3
num_full_keys = 3
num_tran_keys = 2
num_lengths = 3
trans_threshes = np.linspace(60, 2)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes =[20,30]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
g_bond = 15*1
m_bond = 15*1.15
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, g_bond, m_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        T_transitions = [[[[[] for i in range(num_tran_keys)] for j in range(num_tran_keys)] for k in range(num_lengths)] 
                          for l in range(len(filenames))]
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            #frame_vid = frames[:, :, :, 2]# making videos ino a frame list
            #print(frames)



            classes = [("t",0), ("c",0), ("ucf",0)]
            transitions = [("t->t",0), ("t->c",0),
                          ("c->t" ,0), ("c->c",0)]
            times = [("t->t",[[] for i in range(num_lengths)]), ("t->c",[[] for i in range(num_lengths)]),
                          ("c->t" ,[[] for i in range(num_lengths)]), ("c->c",[[] for i in range(num_lengths)])]

            transitions = OrderedDict(transitions)
            times = OrderedDict(times)            
            classes = OrderedDict(classes)
            broken_count = 0
            class_num = 0
            origin = 'ucf'
            last_class = 'ucf'
            last_whole = 0
            state_start = 0
            frame_no = 0
            for fr in frames:
                frame = fr[:, :, 2]
                frame_no += 1
                num_total_frames += 1
                org = total_threshold_filter(frame, frame_no, trans_fil, class_thresh,
                                             broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                                              classes, transitions, times)
                broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len = org
            filtered_len = filtrate_len
            #----------------------------------------------------------------
            ckeys = list(classes.keys())
            clcs = [classes[x] for x in ckeys] # list of frame nums per class
            
            tkeys = list(times.keys())
            tims = [times[x] for x in tkeys]
            
            trkeys = list(transitions.keys())
            trans = [transitions[x] for x in trkeys] #num of each transition
            #ucf = len(sides["ucf"])

            #Top_bottoms[vidnum,:] = [slcs[i] for i in range(len(skeys))]
            Full_classif[vidnum,:] = clcs
            N_transitions[vidnum,:] = np.reshape(trans, (num_tran_keys, num_tran_keys))             
            T_transitions[vidnum] = np.moveaxis(np.reshape(tims, (num_tran_keys, num_tran_keys,num_lengths)),
                                                  [0,1,2], [1,2,0])
            print("T threshold: %s" %trans_fil)
            print("C threshold: %s" %class_thresh)
            print(N_transitions[vidnum,:])
            print(T_transitions[vidnum])
            print(Full_classif[vidnum,:])
        trans_runs[index] = [[Full_classif, (N_transitions, T_transitions), (trans_fil, class_thresh), num_top_keys, num_full_keys,
                                 num_tran_keys,  ckeys, num_tran_keys, num_total_frames], thresholds, params]
        index += 1
        #---------------------------------------------------------------------------------

#-----------------------------------------------------------------------

np.save('trans_runs_destyrene_timesbetween.npy',trans_runs)


['./tchakamau\\Density_matchedstyrene\\45691_15Vpp_0.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_1.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_2.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_4.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_5.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_6.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_7.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_8.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_9.avi']
Number files:  9
Processing vid 0 : ./tchakamau\Density_matchedstyrene\45691_15Vpp_0.avi
T threshold: 60.0
C threshold: 20
[[0. 2.]
 [2. 5.]]
[[[list([]) list([1221, 1914])]
  [list([4722, 10758]) list([5349, 9810, 14180, 2103, 2086])]]

 [[list([]) list([871, 443])]
  [list([3593, 9454]) list([5241, 9699, 12983, 774, 934])]]

 [[list([]) list([350, 1471])]
  [list([1129, 1304]) list([108, 111, 1197, 1329, 1152])]]]
[  952. 49736.  9528.]
Processing vid 1 : ./tchakamau\Den

T threshold: 60.0
C threshold: 30
[[ 4.  8.]
 [ 8. 15.]]
[[[list([2130, 2660, 3563, 552])
   list([4158, 1093, 344, 2095, 3797, 1287, 2291, 935])]
  [list([1094, 7901, 2944, 788, 1369, 394, 14037, 1249])
   list([407, 1613, 607, 390, 1124, 2202, 595, 3936, 1215, 594, 207, 1010, 737, 206, 1440])]]

 [[list([1778, 2065, 3387, 165])
   list([3426, 307, 65, 1479, 3033, 920, 2113, 23])]
  [list([566, 7485, 1645, 209, 609, 256, 12659, 833])
   list([127, 1408, 52, 75, 88, 141, 434, 3228, 1030, 32, 8, 301, 210, 7, 917])]]

 [[list([352, 595, 176, 387])
   list([732, 786, 279, 616, 764, 367, 178, 912])]
  [list([528, 416, 1299, 579, 760, 138, 1378, 416])
   list([280, 205, 555, 315, 1036, 2061, 161, 708, 185, 562, 199, 709, 527, 199, 523])]]]
[17708. 47861.  3891.]
Processing vid 6 : ./tchakamau\Density_matchedstyrene\45696_15Vpp_7.avi
T threshold: 60.0
C threshold: 30
[[2. 3.]
 [3. 4.]]
[[[list([1470, 1024]) list([1727, 7200, 3020])]
  [list([1085, 168, 1534]) list([1716, 716, 1136, 2614])]]


T threshold: 58.816326530612244
C threshold: 30
[[ 0.  1.]
 [ 2. 14.]]
[[[list([]) list([3206])]
  [list([1380, 1528])
   list([1067, 287, 1400, 174, 1128, 1759, 477, 2075, 253, 2087, 334, 224, 1948, 1230])]]

 [[list([]) list([207])]
  [list([67, 3])
   list([0, 15, 16, 24, 22, 48, 76, 1203, 11, 396, 58, 32, 2, 312])]]

 [[list([]) list([2999])]
  [list([1313, 1525])
   list([1067, 272, 1384, 150, 1106, 1711, 401, 872, 242, 1691, 276, 192, 1946, 918])]]]
[2581. 4955.  497.]
Processing vid 3 : ./tchakamau\Density_matchedstyrene\45696_15Vpp_4.avi
T threshold: 58.816326530612244
C threshold: 30
[[4. 8.]
 [7. 8.]]
[[[list([2095, 327, 3269, 1908])
   list([7625, 935, 479, 126, 5284, 632, 449, 4385])]
  [list([301, 603, 602, 992, 1832, 280, 843])
   list([2924, 485, 334, 457, 500, 322, 2036, 1200])]]

 [[list([1818, 102, 2840, 948])
   list([7433, 669, 282, 42, 3764, 209, 1, 3735])]
  [list([8, 423, 424, 427, 768, 12, 77])
   list([2498, 217, 11, 216, 411, 2, 1866, 22])]]

 [[list([277, 225

T threshold: 57.63265306122449
C threshold: 20
[[0. 0.]
 [0. 6.]]
[[[list([]) list([])]
  [list([]) list([4660, 1430, 2230, 1052, 507, 2510])]]

 [[list([]) list([])]
  [list([]) list([3941, 198, 1477, 301, 54, 1359])]]

 [[list([]) list([])]
  [list([]) list([719, 1232, 753, 751, 453, 1151])]]]
[    0. 12805.     0.]
Processing vid 8 : ./tchakamau\Density_matchedstyrene\45696_15Vpp_9.avi
T threshold: 57.63265306122449
C threshold: 20
[[0. 0.]
 [0. 4.]]
[[[list([]) list([])]
  [list([]) list([1771, 361, 430, 2609])]]

 [[list([]) list([])]
  [list([]) list([1612, 71, 44, 1571])]]

 [[list([]) list([])]
  [list([]) list([159, 290, 386, 1038])]]]
[0.0000e+00 1.8636e+04 4.0000e+00]
Processing vid 0 : ./tchakamau\Density_matchedstyrene\45691_15Vpp_0.avi


In [ ]:
"""Pipeline for lists of frames"""
""""""
"""Pipeline for videos:"""
# initialize frame lists
filenames = glob("./tchakamau/De*styrene/*[0-9].avi")# +glob("./tchakamau/W*half/*_[1][0,1,2,3,4,7,8,9]*.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 3
num_full_keys = 3
num_tran_keys = 2
num_lengths = 3
trans_threshes = np.linspace(60, 2)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes =[20,30]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
g_bond = 15*1
m_bond = 15*1.15
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, g_bond, m_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        T_transitions = [[[[[] for i in range(num_tran_keys)] for j in range(num_tran_keys)] for k in range(num_lengths)] 
                          for l in range(len(filenames))]
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            #frame_vid = frames[:, :, :, 2]# making videos ino a frame list
            #print(frames)



            classes = [("t",0), ("c",0), ("ucf",0)]
            transitions = [("t->t",0), ("t->c",0),
                          ("c->t" ,0), ("c->c",0)]
            times = [("t->t",[[] for i in range(num_lengths)]), ("t->c",[[] for i in range(num_lengths)]),
                          ("c->t" ,[[] for i in range(num_lengths)]), ("c->c",[[] for i in range(num_lengths)])]

            transitions = OrderedDict(transitions)
            times = OrderedDict(times)            
            classes = OrderedDict(classes)
            broken_count = 0
            class_num = 0
            origin = 'ucf'
            last_class = 'ucf'
            last_whole = 0
            state_start = 0
            frame_no = 0
            for fr in frames:
                frame = fr[:, :, 2]
                frame_no += 1
                num_total_frames += 1
                org = total_threshold_filter(frame, frame_no, trans_fil, class_thresh,
                                             broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                                              classes, transitions, times)
                broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len = org
            filtered_len = filtrate_len
            #----------------------------------------------------------------
            ckeys = list(classes.keys())
            clcs = [classes[x] for x in ckeys] # list of frame nums per class
            
            tkeys = list(times.keys())
            tims = [times[x] for x in tkeys]
            
            trkeys = list(transitions.keys())
            trans = [transitions[x] for x in trkeys] #num of each transition
            #ucf = len(sides["ucf"])

            #Top_bottoms[vidnum,:] = [slcs[i] for i in range(len(skeys))]
            Full_classif[vidnum,:] = clcs
            N_transitions[vidnum,:] = np.reshape(trans, (num_tran_keys, num_tran_keys))             
            T_transitions[vidnum] = np.moveaxis(np.reshape(tims, (num_tran_keys, num_tran_keys,num_lengths)),
                                                  [0,1,2], [1,2,0])
            print("T threshold: %s" %trans_fil)
            print("C threshold: %s" %class_thresh)
            print(N_transitions[vidnum,:])
            print(T_transitions[vidnum])
            print(Full_classif[vidnum,:])
        trans_runs[index] = [[Full_classif, (N_transitions, T_transitions), (trans_fil, class_thresh), num_top_keys, num_full_keys,
                                 num_tran_keys,  ckeys, num_tran_keys, num_total_frames], thresholds, params]
        index += 1
        #---------------------------------------------------------------------------------

#-----------------------------------------------------------------------

np.save('trans_runs_destyrene_timesbetween.npy',trans_runs)


['./tchakamau\\Density_matchedstyrene\\45691_15Vpp_0.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_1.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_2.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_4.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_5.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_6.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_7.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_8.avi', './tchakamau\\Density_matchedstyrene\\45696_15Vpp_9.avi']
Number files:  9
Processing vid 0 : ./tchakamau\Density_matchedstyrene\45691_15Vpp_0.avi
T threshold: 60.0
C threshold: 20
[[0. 2.]
 [2. 5.]]
[[[list([]) list([1221, 1914])]
  [list([4722, 10758]) list([5349, 9810, 14180, 2103, 2086])]]

 [[list([]) list([871, 443])]
  [list([3593, 9454]) list([5241, 9699, 12983, 774, 934])]]

 [[list([]) list([350, 1471])]
  [list([1129, 1304]) list([108, 111, 1197, 1329, 1152])]]]
[  952. 49736.  9528.]
Processing vid 1 : ./tchakamau\Den