In [1]:
"""This is video reader with all operations inside fnctions, so they can be called on 
    each frame out of a set of frames, and each video out of a set of videos
    """

'This is video reader with all operations inside fnctions, so they can be called on \n    each frame out of a set of frames, and each video out of a set of videos\n    '

In [2]:
"""Imports"""
import matplotlib.pyplot as plt #for maknig plots inside the notebook
import skimage
import skvideo.io
from skvideo.io import vreader, ffprobe
from skimage import measure, morphology, feature
from skimage.filters import *
from skimage.morphology import *
from operator import attrgetter
import numpy as np
import math
from itertools import chain
#from functools import partial, update_wrapper
from scipy import ndimage 
from glob import glob
import seaborn as sns
from collections import OrderedDict 
#import antigravity
blob_doh = skimage.feature.blob_doh

In [3]:
"""Functions"""
# apply total thresholding to each of a list of frames; filter slides with wrong number

def total_threshold_filter(frame, frame_no, transition_threshold, class_thresh,
                           broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                           classes, transitions, times): 
    
   
    
   # ---setup image and detect blobs ----------------
    thresh_img = frame > threshold_isodata(frame)# binary image
        
    phighlight = binary_opening(thresh_img, square(14))
    img = np.copy(frame)
    img[phighlight==0] = 0
    pblobs =blob_doh(img, min_sigma = 10, max_sigma = 16, threshold = 0.007, num_sigma= 15, overlap=0.3)

    ghighlight = binary_opening(
    white_tophat(gaussian(thresh_img, sigma=0.3), square(14)),
                               disk(4))

    img = np.copy(frame)
    img[ghighlight==0] = 0
    gblobs =blob_doh(img, min_sigma = 6, max_sigma = 16, threshold = 0.007, num_sigma= 15, overlap=0.5)


    ngblobs = len(gblobs)
    npblobs = len(pblobs) 
    num_blobs = ngblobs + npblobs
            
    plas_on_glas_dists =[connect((pblob[1], pblob[0]),m_bond, gblobs) for pblob in pblobs]
    num_mconnections = reducer(plas_on_glas_dists)


    plas_on_plas_dists =[connect((pblobs[i][1], pblobs[i][0]),p_bond, pblobs[i+1:]) for i in range(npblobs-1)]
    num_pconnections = reducer(plas_on_plas_dists)



    num_connections = sum([num_pconnections,num_mconnections])
    
    #----------------------filter------------------------- can use actual filter
    test = (num_connections >= expected_connections and num_blobs>=expected_blobs)
    if test: # keep frames that have enough paricles, and are not transitions
        clas=sideify(num_pconnections, num_mconnections )
        
        classes[clas]+=1
            #print(clas)
        
        if clas == 'ucf':
            #broken_count += 1
            #class_num = 0
            #print('ucf')
            pass
        else:
            if origin == 'ucf':
                origin = last_class
                #print("reset origin", origin)
            if clas == last_class:
                class_num += 1
                #print("class_num: %s" %class_num)
            else:
                class_num = 0
                #print("class_reset")
                #print("class_num: %s" %class_num)
            if class_num >= class_thresh: 
                if broken_count >= transition_threshold or clas != origin:
                    transitions[origin + "->" + clas]+=1
                    
                    between_time = frame_no - state_start                               
                    times[origin + "->" + clas][0].append(between_time )

                    stable_time = last_whole - state_start
                    times[origin + "->" + clas][1].append(stable_time)

                    unstable_time = frame_no - last_whole                      
                    times[origin + "->" + clas][2].append(unstable_time)
                
                    state_start = frame_no
                    
                    #print(origin + "->" + clas)
                    origin = clas
                    #print("origin: %s" %origin)
                broken_count = 0
                #print("broken_count: %s" %broken_count)    
                last_whole = frame_no
                
                
            filtrate_len += 1 
            last_class = clas
            
            
    else:
        #print("broken")
        class_num = 0
        #print("class_num: %s" %class_num)
        broken_count += 1
        #print("broken_count: %s" %broken_count)

    return [broken_count, class_num, origin, last_class, last_whole,state_start, filtrate_len]



        
# take largest isodata image region, and return aclassification
def sideify( num_pconnections, num_mconnections):    
    if num_mconnections == 2 and num_pconnections == 3:# and num_mconnections==4: #gtotallengths>48
        return "t"
    elif num_mconnections == 3 and num_pconnections == 2:# and num_mconnections == 4:
        return "c"
    else:
        return "ucf"

def reducer(connections):
    return sum(connections)    
def connect(cv, radius, bloblist): # center of blob2, radius of all blobs, list of other blobs
    num_connections = 0
    norm_radius = 15
    for blob2 in bloblist:
        cv2 = (blob2[1], blob2[0]) # center of blob2
        vector_d = vector_dist(cv, cv2)
        if vector_d <= 2*radius: # blob centers closer than diameter of one blob
            num_connections += 1
        else:
            pass
    return (num_connections)

def vector_dist(v1, v2): # euclidean distance between 2 points
    return math.sqrt(np.sum([(v1[i] - v2[i])**2 for i in range(len(v1))]))

def third_item(l1):
    return l1[2]   

filenames = glob("./tchakamau/W*plastic/4*_14.avi")# +glob("./tchakamau/W*half/*_[1][0,1,2,3,4,7,8,9]*.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 3
num_full_keys = 3
num_tran_keys = 2
trans_threshes = np.linspace(20, 60, 4)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes =[15,22,30]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
p_bond = 15*1.4
m_bond = 15*1.65#1.6
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, p_bond, m_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        Top_bottoms = np.zeros((len(filenames), num_top_keys))
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            #frame_vid = frames[:, :, :, 2]# making videos ino a frame list
            #print(frames)



            sides = {"t":[], "c":[], "ucf":[]}
            classes = {"t":[], "c":[], "ucf":[]}
            transitions = [("t->t",[]), ("t->c",[]),
                          ("c->t" ,[]), ("c->c",[])]

            transitions = OrderedDict(transitions)
            broken_count = 0
            class_num = 0
            origin = 'ucf'
            last_class = 'ucf'
            last_whole = 0
            for fr in frames:
                frame = fr[:, :, 2]
                num_total_frames += 1
                org = total_threshold_filter(frame, num_total_frames, trans_fil, class_thresh,
                                             broken_count, class_num, origin, last_class, last_whole, filtrate_len, 
                                             sides, classes, transitions)
                broken_count, class_num, origin, last_class, last_whole, filtrate_len = org
            filtered_len = filtrate_len
            #----------------------------------------------------------------
            trans_len = len([y for x in transitions.values() for y in x])
            skeys = list(sides.keys())
            ckeys = list(classes.keys())
            tkeys = list(transitions.keys())
            slcs = [len(sides[x]) for x in skeys]
            clcs = [len(classes[x]) for x in ckeys]
            trans = [len(transitions[x]) for x in tkeys] #num of each transition
            ucf = len(sides["ucf"])


            Top_bottoms[vidnum,:] = [slcs[i] for i in range(len(skeys))]
            Full_classif[vidnum,:] = [clcs[i] for i in range(len(ckeys))]
            N_transitions[vidnum,:] = np.reshape(trans, (num_tran_keys, num_tran_keys))
            print("T threshold: %s" %trans_fil)
            print("C threshold: %s" %class_thresh)
            print(N_transitions[vidnum,:])
            #print("finished vid %s" %vidnum)
        trans_runs[index] = [[Top_bottoms, Full_classif, N_transitions, (trans_fil, class_thresh), num_top_keys, num_full_keys,
                                 num_tran_keys, skeys, ckeys, num_tran_keys, num_total_frames], thresholds, params]
        index += 1
        #---------------------------------------------------------------------------------

#-----------------------------------------------------------------------

np.save('trans_runs_plas15.5.npy',trans_runs)


In [ ]:
"""Pipeline for lists of frames"""
""""""
"""Pipeline for videos:"""
# initialize frame lists
filenames = glob("./tchakamau/W*plastic/4*avi")# +glob("./tchakamau/W*half/*_[1][0,1,2,3,4,7,8,9]*.avi")  #[1,2,3,4,6,7,8,9]["./tchakamau/New_setup/45681_10Vpp_25.avi"
filenames.sort()
print(filenames)
num_top_keys = 3
num_full_keys = 3
num_tran_keys = 2
num_lengths = 3
trans_threshes = np.linspace(30, 50, 2)#[30, 40, 50]#[5, 8, 10, 19, 27, 38, 52, 60]
class_threshes =[20,30]
trans_runs = {}
#trans_fil = 10

ave = np.average
expected_blobs = 4
expected_connections = 5
p_bond = 15*1.4
m_bond = 15*1.65#1.6
    
"""area_threshold = 1800   # must have enough particles
convex_thresholds = (2000, 2800)   # convex hull area (> 2500 filtered)  # particles must be in parallelogram
minor_thresholds = (38, 48) # minor_axis length (< filterd) # particles must be in parallelogram
major_thresholds = (59, 76)"""
thresholds = [expected_blobs , expected_connections, p_bond, m_bond]
params = [3, 115, 98, 2, 95, 80]
print("Number files: ", len(filenames))
index = 0
for trans_fil in trans_threshes:
    
    for class_thresh in class_threshes:
        
        Full_classif = np.zeros((len(filenames), num_full_keys))
        N_transitions = np.zeros((len(filenames), num_tran_keys, num_tran_keys))
        T_transitions = [[[[[] for i in range(num_tran_keys)] for j in range(num_tran_keys)] for k in range(num_lengths)] 
                          for l in range(len(filenames))]
        num_total_frames = 0 
        filtrate_len = 0
        for vidnum in range(len(filenames)):
            print("Processing vid %s : %s" %(vidnum, filenames[vidnum]))
            #meta = ffprobe(filenames[vidnum])
            #print(meta)#['@nb_frames'])
            #print(5)
            frames = vreader(filenames[vidnum])
            #frame_vid = frames[:, :, :, 2]# making videos ino a frame list
            #print(frames)



            
            classes = [("t",0), ("c",0), ("ucf",0)]
            transitions = [("t->t",0), ("t->c",0),
                          ("c->t" ,0), ("c->c",0)]
            times = [("t->t",[[] for i in range(num_lengths)]), ("t->c",[[] for i in range(num_lengths)]),
                          ("c->t" ,[[] for i in range(num_lengths)]), ("c->c",[[] for i in range(num_lengths)])]

            transitions = OrderedDict(transitions)
            times = OrderedDict(times)            
            classes = OrderedDict(classes)
            broken_count = 0
            class_num = 0
            origin = 'ucf'
            last_class = 'ucf'
            last_whole = 0
            state_start = 0
            frame_no = 0
            for fr in frames:
                frame = fr[:, :, 2]
                frame_no += 1
                num_total_frames += 1
                org = total_threshold_filter(frame, frame_no, trans_fil, class_thresh,
                                             broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len, 
                                              classes, transitions, times)
                broken_count, class_num, origin, last_class, last_whole, state_start, filtrate_len = org
            filtered_len = filtrate_len
            #----------------------------------------------------------------
             
            ckeys = list(classes.keys())
            clcs = [classes[x] for x in ckeys] # list of frame nums per class
            
            tkeys = list(times.keys())
            tims = [times[x] for x in tkeys]
            
            trkeys = list(transitions.keys())
            trans = [transitions[x] for x in trkeys] #num of each transition
            #ucf = len(sides["ucf"])

            #Top_bottoms[vidnum,:] = [slcs[i] for i in range(len(skeys))]
            Full_classif[vidnum,:] = clcs
            N_transitions[vidnum,:] = np.reshape(trans, (num_tran_keys, num_tran_keys))             
            T_transitions[vidnum] = np.moveaxis(np.reshape(tims, (num_tran_keys, num_tran_keys,num_lengths)),
                                                  [0,1,2], [1,2,0])
            print("T threshold: %s" %trans_fil)
            print("C threshold: %s" %class_thresh)
            print(N_transitions[vidnum,:])
            print(T_transitions[vidnum])
            print(Full_classif[vidnum,:])
        trans_runs[index] = [[Full_classif, (N_transitions, T_transitions), (trans_fil, class_thresh), num_top_keys, num_full_keys,
                                 num_tran_keys, ckeys, num_tran_keys, num_total_frames], thresholds, params]
        index += 1
        #---------------------------------------------------------------------------------

#-----------------------------------------------------------------------

np.save('trans_runs_plas15.5_timesbetween.npy',trans_runs)


['./tchakamau\\Washed15vplastic\\45659_15Vpp_7.avi', './tchakamau\\Washed15vplastic\\45660_15Vpp_3.avi', './tchakamau\\Washed15vplastic\\45660_15Vpp_4.avi', './tchakamau\\Washed15vplastic\\45660_15Vpp_5_separate.avi', './tchakamau\\Washed15vplastic\\45660_15Vpp_6.avi', './tchakamau\\Washed15vplastic\\45661_15Vpp_11.avi', './tchakamau\\Washed15vplastic\\45661_15Vpp_18.avi', './tchakamau\\Washed15vplastic\\45661_15Vpp_8.avi', './tchakamau\\Washed15vplastic\\45688_15Vpp_12.avi', './tchakamau\\Washed15vplastic\\45697_15Vpp_15.avi', './tchakamau\\Washed15vplastic\\45697_15Vpp_16.avi', './tchakamau\\Washed15vplastic\\45697_15Vpp_17.avi', './tchakamau\\Washed15vplastic\\45731_15Vpp_0.avi', './tchakamau\\Washed15vplastic\\45748_15Vpp_1.avi', './tchakamau\\Washed15vplastic\\45753_15Vpp_10.avi', './tchakamau\\Washed15vplastic\\45753_15Vpp_9.avi', './tchakamau\\Washed15vplastic\\45760_15Vpp_13.avi', './tchakamau\\Washed15vplastic\\45760_15Vpp_14.avi', './tchakamau\\Washed15vplastic\\45779_15Vpp_1

T threshold: 30.0
C threshold: 20
[[11.  3.]
 [ 3.  2.]]
[[[list([788, 285, 1040, 1113, 1744, 557, 2382, 504, 878, 1083, 1154])
   list([6436, 492, 826])]
  [list([668, 8324, 4091]) list([1785, 413])]]

 [[list([684, 127, 45, 990, 889, 130, 1184, 106, 215, 654, 810])
   list([6257, 218, 644])]
  [list([297, 8285, 3965]) list([1446, 271])]]

 [[list([104, 158, 995, 123, 855, 427, 1198, 398, 663, 429, 344])
   list([179, 274, 182])]
  [list([371, 39, 126]) list([339, 142])]]]
[23408. 14137.  8157.]
Processing vid 17 : ./tchakamau\Washed15vplastic\45760_15Vpp_14.avi
T threshold: 30.0
C threshold: 20
[[10.  4.]
 [ 4.  0.]]
[[[list([4304, 518, 1159, 1857, 325, 1850, 327, 607, 1491, 519])
   list([221, 519, 2882, 551])]
  [list([8038, 1291, 275, 2559]) list([])]]

 [[list([3671, 407, 508, 815, 1, 1659, 55, 145, 1071, 141])
   list([27, 35, 2830, 244])]
  [list([7942, 1244, 64, 2279]) list([])]]

 [[list([633, 111, 651, 1042, 324, 191, 272, 462, 420, 378])
   list([194, 484, 52, 307])]
  [lis

T threshold: 30.0
C threshold: 30
[[11.  3.]
 [ 3.  2.]]
[[[list([789, 284, 1101, 1052, 1744, 557, 2382, 504, 878, 1083, 1154])
   list([6446, 492, 826])]
  [list([668, 8324, 4090]) list([1785, 414])]]

 [[list([674, 116, 35, 919, 879, 120, 1174, 96, 205, 644, 800])
   list([6257, 208, 634])]
  [list([287, 8275, 3928]) list([1436, 261])]]

 [[list([115, 168, 1066, 133, 865, 437, 1208, 408, 673, 439, 354])
   list([189, 284, 192])]
  [list([381, 49, 162]) list([349, 153])]]]
[23408. 14137.  8157.]
Processing vid 17 : ./tchakamau\Washed15vplastic\45760_15Vpp_14.avi
T threshold: 30.0
C threshold: 30
[[9. 4.]
 [4. 0.]]
[[[list([4315, 518, 1159, 2183, 1849, 362, 572, 1508, 502])
   list([220, 519, 2882, 551])]
  [list([8038, 1291, 275, 2559]) list([])]]

 [[list([3671, 397, 498, 805, 1648, 45, 100, 1061, 73])
   list([16, 25, 2820, 234])]
  [list([7932, 1234, 54, 2269]) list([])]]

 [[list([644, 121, 661, 1378, 201, 317, 472, 447, 429])
   list([204, 494, 62, 317])]
  [list([106, 57, 221, 2